export const LAB_TEST_OPTIONS = [
  // Blood Tests - Basic
  "Complete blood count (CBC)",
  "Comprehensive metabolic panel (CMP)",
  "Basic metabolic panel (BMP)",
  "Blood sugar fasting",
  "Blood sugar post-prandial (PP)",
  "Random blood sugar",
  "HbA1c (Glycated haemoglobin)",
  "Lipid profile",
  "Liver function test (LFT)",
  "Kidney function test (KFT)",
  "Electrolytes (Na / K / Cl)",
  "Uric acid",
  "CRP (C-reactive protein)",
  "ESR (Erythrocyte sedimentation rate)",
  "Ferritin",
  "Iron studies (Serum iron, TIBC, transferrin saturation)",
  "Haemoglobin (Hb)",
  "Peripheral blood smear",
  "Reticulocyte count",
  "Prothrombin time (PT / INR)",
  "APTT",
  "D-Dimer",

  // Hormonal / Endocrine
  "Thyroid panel (T3 / T4 / TSH)",
  "Free T3 (FT3)",
  "Free T4 (FT4)",
  "Anti-TPO antibodies",
  "Anti-thyroglobulin antibodies",
  "Cortisol (morning)",
  "DHEA-S",
  "Testosterone (total)",
  "Free testosterone",
  "LH (Luteinising hormone)",
  "FSH (Follicle stimulating hormone)",
  "Prolactin",
  "Oestradiol (E2)",
  "Progesterone",
  "Beta HCG (Pregnancy test)",
  "AMH (Anti-Müllerian hormone)",
  "Insulin fasting",
  "C-peptide",
  "ACTH (Adrenocorticotropic hormone)",
  "Parathyroid hormone (PTH)",

  // Vitamin & Nutrition
  "Vitamin D3 (25-OH)",
  "Vitamin B12",
  "Folate (Folic acid)",
  "Zinc",
  "Magnesium",
  "Calcium (serum)",
  "Phosphorus",
  "Copper",
  "Selenium",

  // Cardiac Markers
  "ECG (12-lead)",
  "Troponin I",
  "Troponin T",
  "CK-MB (Creatine kinase MB)",
  "LDH (Lactate dehydrogenase)",
  "BNP (Brain natriuretic peptide)",
  "NT-proBNP",
  "Homocysteine",
  "Lipoprotein (a)",
  "ApoB / ApoA1 ratio",

  // Urine Tests
  "Urinalysis (routine & microscopy)",
  "Urine culture & sensitivity",
  "Urine protein (spot)",
  "Urine creatinine",
  "24-hour urine protein",
  "Microalbumin (urine)",
  "Urine pregnancy test",

  // Infectious Disease
  "COVID-19 RT-PCR",
  "COVID-19 rapid antigen",
  "Dengue NS1 antigen",
  "Dengue IgG / IgM",
  "Malaria antigen (PF/PV)",
  "Typhoid (Widal / Typhidot IgM)",
  "Hepatitis B surface antigen (HBsAg)",
  "Hepatitis B surface antibody (HBsAb)",
  "Hepatitis B core antibody (HBcAb)",
  "Hepatitis C antibody (Anti-HCV)",
  "HIV 1 & 2 (ELISA / rapid)",
  "Syphilis (VDRL / TPHA)",
  "Chikungunya IgM",
  "Leptospirosis IgM",
  "Scrub typhus IgM",
  "H. pylori antigen (stool)",
  "H. pylori antibody (serum)",
  "Strep throat rapid test",

  // Allergy & Immunology
  "Total IgE",
  "Food allergy panel",
  "Inhalant allergy panel",
  "ANA (Antinuclear antibody)",
  "Anti-dsDNA",
  "Rheumatoid factor (RF)",
  "Anti-CCP antibody",
  "C3 / C4 complement",
  "ANCA (pANCA / cANCA)",

  // Cancer Markers
  "PSA (Prostate specific antigen)",
  "Free PSA",
  "CA-125",
  "CA 19-9",
  "CEA (Carcinoembryonic antigen)",
  "AFP (Alpha-fetoprotein)",
  "CA 15-3",
  "Beta-2 microglobulin",
  "LDH (tumour marker)",

  // Imaging & Radiology
  "Chest X-Ray (PA view)",
  "X-Ray spine (cervical)",
  "X-Ray spine (lumbar)",
  "X-Ray knee",
  "X-Ray pelvis",
  "X-Ray hand / wrist",
  "Ultrasound abdomen (whole)",
  "Ultrasound pelvis",
  "Ultrasound obstetric (dating scan)",
  "Ultrasound thyroid",
  "Ultrasound scrotum",
  "Ultrasound Doppler (lower limb)",

  // Stool Tests
  "Stool routine & microscopy",
  "Stool culture",
  "Occult blood (stool)",
  "Calprotectin (stool)",

  // Genetic & Specialised
  "Karyotyping",
  "HLA-B27",
  "G6PD enzyme activity",
  "Sickle cell screening",
  "Thalassemia carrier screen (HPLC)",
  "BRCA1 / BRCA2",
  "Pharmacogenomics panel",
];
